import { MenuItem } from '../types';

export const menu: MenuItem[] = [
  {
    id: 'spicy_chicken_sandwich',
    name: 'Spicy Chicken Sandwich',
    category: 'Mains',
    description: 'Crispy fried chicken, sriracha honey, pickled slaw, potato roll.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?q=80&w=1200&auto=format&fit=crop',
    tags: ['spicy', 'popular'],
    spiceLevel: 3,
    calories: 720,
    ingredients: ['crispy chicken', 'sriracha honey', 'pickled slaw', 'potato roll'],
    modifiers: { remove: ['sriracha honey', 'pickled slaw'], addOns: ['ranch', 'avocado', 'extra chicken'] }
  },
  {
    id: 'classic_bistro_burger',
    name: 'Truffle Wagyu Burger',
    category: 'Mains',
    description: 'A5 wagyu patty, black truffle aioli, aged gruyere, brioche bun.',
    price: 34,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=1200&auto=format&fit=crop',
    tags: ['premium', 'protein'],
    spiceLevel: 0,
    calories: 910,
    ingredients: ['wagyu patty', 'truffle aioli', 'aged gruyere', 'brioche bun'],
    modifiers: { remove: ['truffle aioli', 'gruyere'], addOns: ['bacon', 'avocado', 'ranch'] }
  },
  {
    id: 'veggie_power_bowl',
    name: 'Lobster Risotto',
    category: 'Mains',
    description: 'Maine lobster, arborio rice, saffron, parmesan, chive oil.',
    price: 38,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=1200&auto=format&fit=crop',
    tags: ['premium', 'gluten-free'],
    spiceLevel: 0,
    calories: 760,
    ingredients: ['maine lobster', 'arborio rice', 'saffron', 'parmesan', 'chive oil'],
    modifiers: { remove: ['parmesan', 'chive oil'], addOns: ['extra lobster', 'asparagus'] }
  },
  {
    id: 'neon_caesar_salad',
    name: 'Pan-Seared Salmon',
    category: 'Mains',
    description: 'Atlantic salmon, lemon beurre blanc, roasted asparagus, dill.',
    price: 32,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=1200&auto=format&fit=crop',
    tags: ['gluten-free', 'healthy'],
    spiceLevel: 0,
    calories: 610,
    ingredients: ['atlantic salmon', 'lemon beurre blanc', 'asparagus', 'dill'],
    modifiers: { remove: ['beurre blanc'], addOns: ['side salad', 'lemon'] }
  },
  {
    id: 'quantum_fries',
    name: 'Truffle Fries',
    category: 'Sides',
    description: 'Crispy fries, parmesan, black truffle salt, garlic aioli.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=1200&auto=format&fit=crop',
    tags: ['vegetarian'],
    spiceLevel: 0,
    calories: 520,
    ingredients: ['crispy fries', 'parmesan', 'truffle salt', 'garlic aioli'],
    modifiers: { sizes: ['regular', 'large'], remove: ['parmesan', 'aioli'], addOns: ['ranch', 'chili crisp'] }
  },
  {
    id: 'lunar_lemonade',
    name: 'Artisan Lemonade',
    category: 'Drinks',
    description: 'House-made lavender, elderflower, sparkling citrus.',
    price: 8,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?q=80&w=1200&auto=format&fit=crop',
    tags: ['refreshing'],
    spiceLevel: 0,
    calories: 120,
    ingredients: ['lemon', 'lavender', 'elderflower', 'sparkling water'],
    modifiers: { sizes: ['regular', 'large'], addOns: ['extra mint', 'less sugar'] }
  },
  {
    id: 'large_water',
    name: 'Large Water',
    category: 'Drinks',
    description: 'Filtered still water, chilled over clear ice.',
    price: 3,
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?q=80&w=1200&auto=format&fit=crop',
    tags: ['refreshing'],
    spiceLevel: 0,
    calories: 0,
    ingredients: ['filtered water', 'clear ice'],
    modifiers: { addOns: ['lemon', 'mint'] }
  },
  {
    id: 'espresso_martini',
    name: 'Espresso Martini',
    category: 'Drinks',
    description: 'Vodka, kahlua, fresh espresso, vanilla.',
    price: 16,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=1200&auto=format&fit=crop',
    tags: ['alcoholic'],
    spiceLevel: 0,
    calories: 180,
    ingredients: ['vodka', 'kahlua', 'espresso', 'vanilla'],
    modifiers: { addOns: ['extra espresso', 'vanilla foam'] }
  },
  {
    id: 'stellar_chocolate_mousse',
    name: 'Molten Chocolate Cake',
    category: 'Desserts',
    description: 'Dark chocolate, vanilla bean ice cream, gold leaf.',
    price: 16,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=1200&auto=format&fit=crop',
    tags: ['vegetarian', 'signature'],
    spiceLevel: 0,
    calories: 580,
    ingredients: ['dark chocolate', 'vanilla bean ice cream', 'gold leaf'],
    modifiers: { remove: ['ice cream'], addOns: ['espresso dust', 'extra ganache'] }
  },
  {
    id: 'creme_brulee',
    name: 'Creme Brulee',
    category: 'Desserts',
    description: 'Madagascar vanilla, caramelized sugar, seasonal berries.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?q=80&w=1200&auto=format&fit=crop',
    tags: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    calories: 430,
    ingredients: ['vanilla custard', 'caramelized sugar', 'seasonal berries'],
    modifiers: { remove: ['berries'], addOns: ['espresso dust'] }
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    category: 'Desserts',
    description: 'Mascarpone, espresso-soaked ladyfingers, cocoa.',
    price: 14,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=1200&auto=format&fit=crop',
    tags: ['vegetarian'],
    spiceLevel: 0,
    calories: 520,
    ingredients: ['mascarpone', 'espresso', 'ladyfingers', 'cocoa'],
    modifiers: { addOns: ['extra cocoa', 'cream'] }
  }
];
